### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Rzezimioszek/QGIS-style-exporter#1]
Please fix the metadata.txt links in your plugin repository, they should link to this repo not your profile on github

**Comment by Rzezimioszek** [comment]
Hi,

I fixed metadata in new version (0.2) become in mean while I made bugs
fixes.

Regards,
Łukasz Świątek

śr., 6 mar 2024, 07:39 użytkownik mazano ***@***.***> napisał:

**Comment by NyakudyaA** [comment]
Hi the issue tracker links is still wrong, it should be https://github.com/Rzezimioszek/QGIS-style-exporter not https://github.com/Rzezimioszek/QGIS-style-exporter/blob/main/style_exporter/metadata.txt#L15 

Also delete https://github.com/Rzezimioszek/QGIS-style-exporter/tree/main/style_exporter/__pycache__ this autogenerated on install

**Comment by Rzezimioszek** [comment]
Hi,

I hope this time is everything fine. Thanks for help,  this is my first
plugin, sorry for problem.

Regards,
Łukasz Świątek

czw., 7 mar 2024, 08:05 użytkownik mazano ***@***.***>
napisał:

**Comment by NyakudyaA** [comment]
You haven't addressed any of the issues I mentioned. PLease adjust https://github.com/Rzezimioszek/QGIS-style-exporter/blob/main/style_exporter/metadata.txt and delete the __pycache folder. Once you have done so please upload a new version to qgis plugin repo

**Comment by NyakudyaA** [comment]
Hi @Rzezimioszek Please update both

**Comment by Rzezimioszek** [comment]
I already did

**Comment by NyakudyaA** [comment]
@Rzezimioszek Please check the screenshot below
<img width="919" alt="Screenshot 2024-03-20 at 10 12 25" src="https://github.com/Rzezimioszek/QGIS-style-exporter/assets/2510900/6e295d86-8886-4fc8-9db9-5c25b412022e">

**Comment by Rzezimioszek** [comment]
I think, now is ok.

![image](https://github.com/Rzezimioszek/QGIS-style-exporter/assets/105981729/7c008809-2b82-4f1e-862d-4b53a9b00524)
